# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Glarner Berggeiss
email: glarnerberggeiss@bluewin.ch
description: >- 
    Die "Glarner Berggeiss Berglauf in Braunwald" ist ein Berglauf von Linthal (GL) 
    nach Braunwald. Am Freitag 25. August 2023 findet die 4.Ausgabe statt. 
    Die Anmeldung öffnet am 1.Mai.
 
baseurl: # "/GB_page" # the subpath of your site, e.g. /blog
url: https://glarnerberggeiss.com 

# Build settings
remote_theme: spretosg/bulma-clean-theme
plugins:
    - jekyll-feed
    - jekyll-remote-theme
    
google_analytics: G-GVLZHZ8HSQ
google_analytics: UA-186957857-1

# footer_menu: sponsors_footer

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
